### ISSUE TITLE
Link to JRuby+Truffle source code

### ISSUE THREAD

**Issue by hastebrot** [chrisseaton/chrisseaton.com#1]
Hi!

The Truffle source code linked in `content/rubytruffle/index.md` seems to have moved 

- from https://github.com/jruby/jruby/tree/master/core/src/main/java/org/jruby/truffle 
- to https://github.com/jruby/jruby/tree/master/truffle/src/main/java/org/jruby/truffle.

&mdash;Benjamin

**Comment by chrisseaton** [comment]
Fixed in 2c0392574532fd0176cfaeb6b6c965aac8d67722. Thanks very much.
